myproject/core/urls.py
from django.urls import path
from myproject.core import views as v


app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
    path('blank/', v.blank, name='blank'),
    path('email/', v.email, name='email'),
    path('compose/', v.compose, name='compose'),
    path('calendar/', v.calendar, name='calendar'),
    path('chat/', v.chat, name='chat'),
    path('charts/', v.charts, name='charts'),
    path('forms/', v.forms, name='forms'),
    path('ui/', v.ui, name='ui'),
    path('basic_table/', v.basic_table, name='basic_table'),
    path('datatable/', v.datatable, name='datatable'),
    path('google_maps/', v.google_maps, name='google_maps'),
    path('vector_maps/', v.vector_maps, name='vector_maps'),
    path('p404/', v.p404, name='p404'),
    path('p500/', v.p500, name='p500'),
    path('signin/', v.signin, name='signin'),
    path('signup/', v.signup, name='signup'),
    path('buttons/', v.buttons, name='buttons'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myproject.core.urls')),
    path('admin/', admin.site.urls),
]

myproject/core/models.py
from django.db import models

# Create your models here.

myproject/core/views.py
from django.shortcuts import render


def index(request):
    template_name = 'index.html'
    return render(request, template_name)


def blank(request):
    template_name = 'blank.html'
    return render(request, template_name)


def email(request):
    template_name = 'email.html'
    return render(request, template_name)


def compose(request):
    template_name = 'compose.html'
    return render(request, template_name)


def calendar(request):
    template_name = 'calendar.html'
    return render(request, template_name)


def chat(request):
    template_name = 'chat.html'
    return render(request, template_name)


def charts(request):
    template_name = 'charts.html'
    return render(request, template_name)


def forms(request):
    template_name = 'forms.html'
    return render(request, template_name)


def ui(request):
    template_name = 'ui.html'
    return render(request, template_name)


def basic_table(request):
    template_name = 'basic-table.html'
    return render(request, template_name)


def datatable(request):
    template_name = 'datatable.html'
    return render(request, template_name)


def google_maps(request):
    template_name = 'google-maps.html'
    return render(request, template_name)


def vector_maps(request):
    template_name = 'vector-maps.html'
    return render(request, template_name)


def p404(request):
    template_name = '404.html'
    return render(request, template_name)


def p500(request):
    template_name = '500.html'
    return render(request, template_name)


def signin(request):
    template_name = 'signin.html'
    return render(request, template_name)


def signup(request):
    template_name = 'signup.html'
    return render(request, template_name)


def buttons(request):
    template_name = 'buttons.html'
    return render(request, template_name)

myproject/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="shortcut icon" href="{% static 'img/logo.png' %}">
  <title>{% block title %}Adminator{% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="app">
  <!-- @TOC -->
  <!-- =================================================== -->
  <!--
      + @Page Loader
      + @App Content
          - #Left Sidebar
              > $Sidebar Header
              > $Sidebar Menu

          - #Main
              > $Topbar
              > $App Screen Content
    -->
  <!-- @Page Loader -->
  <!-- =================================================== -->
  {% block loader %}
  <!-- <div id='loader'>
      <div class="spinner"></div>
    </div>
    <script src="{% static 'js/load.js' %}"></script> -->
  {% endblock loader %}
  <!-- @App Content -->
  <!-- =================================================== -->
  <div>
    {% include "includes/sidebar.html" %}
    <!-- #Main ============================ -->
    <div class="page-container">
      <!-- ### $Topbar ### -->
      {% include "includes/topbar.html" %}
      <!-- ### $App Screen Content ### -->
      <main class='main-content bgc-grey-100'>
        <div id='mainContent'>
          {% block content %}
          <div class="full-container">
          </div>
          {% endblock content %}
        </div>
      </main>
      {% include "includes/footer.html" %}
    </div>
  </div>
  <script src="{% static 'js/vendor.js' %}"></script>
  <script src="{% static 'js/bundle.js' %}"></script>
</body>

</html>

myproject/core/templates/basic-table.html
{% extends "base.html" %}
{% load static %}
{% block title %}Basic Table{% endblock title %}
{% block content %}
<div class="container-fluid">
  <h4 class="c-grey-900 mT-10 mB-30">Basic Tables</h4>
  <div class="row">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <h4 class="c-grey-900 mB-20">Simple Table</h4>
        <p>Using the most basic table markup, here’s how <code class="highlighter-rouge">.table</code>-based tables look in Bootstrap. <strong>All table styles are inherited in Bootstrap 4</strong>, meaning any nested tables will be styled in the same manner as the parent.</p>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">First Name</th>
              <th scope="col">Last Name</th>
              <th scope="col">Username</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">1</th>
              <td>Mark</td>
              <td>Otto</td>
              <td>@mdo</td>
            </tr>
            <tr>
              <th scope="row">2</th>
              <td>Jacob</td>
              <td>Thornton</td>
              <td>@fat</td>
            </tr>
            <tr>
              <th scope="row">3</th>
              <td>Larry</td>
              <td>the Bird</td>
              <td>@twitter</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <h4 class="c-grey-900 mB-20">Table head options</h4>
        <p>Similar to tables and dark tables, use the modifier classes <code class="highlighter-rouge">.thead-light</code> or <code class="highlighter-rouge">.thead-dark</code> to make <code class="highlighter-rouge">&lt;thead&gt;</code>s appear light or dark gray.</p>
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">#</th>
              <th scope="col">First Name</th>
              <th scope="col">Last Name</th>
              <th scope="col">Username</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">1</th>
              <td>Mark</td>
              <td>Otto</td>
              <td>@mdo</td>
            </tr>
            <tr>
              <th scope="row">2</th>
              <td>Jacob</td>
              <td>Thornton</td>
              <td>@fat</td>
            </tr>
            <tr>
              <th scope="row">3</th>
              <td>Larry</td>
              <td>the Bird</td>
              <td>@twitter</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <h4 class="c-grey-900 mB-20">Striped rows</h4>
        <p>Use <code class="highlighter-rouge">.table-striped</code> to add zebra-striping to any table row within the <code class="highlighter-rouge">&lt;tbody&gt;</code>.</p>
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">First Name</th>
              <th scope="col">Last Name</th>
              <th scope="col">Username</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">1</th>
              <td>Mark</td>
              <td>Otto</td>
              <td>@mdo</td>
            </tr>
            <tr>
              <th scope="row">2</th>
              <td>Jacob</td>
              <td>Thornton</td>
              <td>@fat</td>
            </tr>
            <tr>
              <th scope="row">3</th>
              <td>Larry</td>
              <td>the Bird</td>
              <td>@twitter</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <h4 class="c-grey-900 mB-20">Bordered table</h4>
        <p>Add <code class="highlighter-rouge">.table-bordered</code> for borders on all sides of the table and cells.</p>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">First Name</th>
              <th scope="col">Last Name</th>
              <th scope="col">Username</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">1</th>
              <td>Mark</td>
              <td>Otto</td>
              <td>@mdo</td>
            </tr>
            <tr>
              <th scope="row">2</th>
              <td>Mark</td>
              <td>Otto</td>
              <td>@TwBootstrap</td>
            </tr>
            <tr>
              <th scope="row">3</th>
              <td>Jacob</td>
              <td>Thornton</td>
              <td>@fat</td>
            </tr>
            <tr>
              <th scope="row">4</th>
              <td colspan="2">Larry the Bird</td>
              <td>@twitter</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20">
        <h4 class="c-grey-900 mB-20">Hoverable rows</h4>
        <p>Add <code class="highlighter-rouge">.table-hover</code> to enable a hover state on table rows within a <code class="highlighter-rouge">&lt;tbody&gt;</code>.</p>
        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">First Name</th>
              <th scope="col">Last Name</th>
              <th scope="col">Username</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">1</th>
              <td>Mark</td>
              <td>Otto</td>
              <td>@mdo</td>
            </tr>
            <tr>
              <th scope="row">2</th>
              <td>Jacob</td>
              <td>Thornton</td>
              <td>@fat</td>
            </tr>
            <tr>
              <th scope="row">3</th>
              <td colspan="2">Larry the Bird</td>
              <td>@twitter</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

myproject/core/templates/blank.html
{% extends "base.html" %}
{% load static %}
{% block title %}Blank{% endblock title %}
{% block content %}
<div class="full-container">
</div>
{% endblock content %}

myproject/core/templates/buttons.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="shortcut icon" href="{% static 'img/logo.png' %}">
  <title></title>
  <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
</head>

<body class="app">
  <!-- @TOC -->
  <!-- =================================================== -->
  <!--
      + @Page Loader
      + @App Content
          - #Left Sidebar
              > $Sidebar Header
              > $Sidebar Menu

          - #Main
              > $Topbar
              > $App Screen Content
    -->
  <!-- @Page Loader -->
  <!-- =================================================== -->
  <div id='loader' class="pos-f h-100vh w-100 bgc-deep-purple-50 z-9">
    <div class="spinner"></div>
  </div>
  <script>
    window.addEventListener('load', function load() {
        const loader = document.getElementById('loader');
        setTimeout(function() {
          loader.classList.add('fadeOut');
        }, 3000);
      });
    </script>
  <!-- @App Content -->
  <!-- =================================================== -->
  <div>
    {% include "includes/sidebar.html" %}
    <!-- #Main ============================ -->
    <div class="page-container">
      <!-- ### $Topbar ### -->
      <div class="header navbar">
        <div class="header-container">
          <ul class="nav-left">
            <li>
              <a id='sidebar-toggle' class="sidebar-toggle" href="javascript:void(0);">
                <i class="ti-menu"></i>
              </a>
            </li>
            <li class="search-box">
              <a class="search-toggle no-pdd-right" href="javascript:void(0);">
                <i class="search-icon ti-search pdd-right-10"></i>
                <i class="search-icon-close ti-close pdd-right-10"></i>
              </a>
            </li>
            <li class="search-input">
              <input class="form-control" type="text" placeholder="Search...">
            </li>
          </ul>
          <ul class="nav-right">
            <li class="notifications dropdown">
              <span class="counter bgc-red">3</span>
              <a href="" class="dropdown-toggle no-after" data-toggle="dropdown">
                <i class="ti-bell"></i>
              </a>
              <ul class="dropdown-menu">
                <li class="pX-20 pY-15 bdB">
                  <i class="ti-bell pR-10"></i>
                  <span class="fsz-sm fw-600 c-grey-900">Notifications</span>
                </li>
                <li>
                  <ul class="ovY-a pos-r scrollable lis-n p-0 m-0 fsz-sm">
                    <li>
                      <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                        <div class="peer mR-15">
                          <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/1.jpg" alt="">
                        </div>
                        <div class="peer peer-greed">
                          <span>
                            <span class="fw-500">John Doe</span>
                            <span class="c-grey-600">liked your <span class="text-dark">post</span>
                            </span>
                          </span>
                          <p class="m-0">
                            <small class="fsz-xs">5 mins ago</small>
                          </p>
                        </div>
                      </a>
                    </li>
                    <li>
                      <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                        <div class="peer mR-15">
                          <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/2.jpg" alt="">
                        </div>
                        <div class="peer peer-greed">
                          <span>
                            <span class="fw-500">Moo Doe</span>
                            <span class="c-grey-600">liked your <span class="text-dark">cover image</span>
                            </span>
                          </span>
                          <p class="m-0">
                            <small class="fsz-xs">7 mins ago</small>
                          </p>
                        </div>
                      </a>
                    </li>
                    <li>
                      <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                        <div class="peer mR-15">
                          <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/3.jpg" alt="">
                        </div>
                        <div class="peer peer-greed">
                          <span>
                            <span class="fw-500">Lee Doe</span>
                            <span class="c-grey-600">commented on your <span class="text-dark">video</span>
                            </span>
                          </span>
                          <p class="m-0">
                            <small class="fsz-xs">10 mins ago</small>
                          </p>
                        </div>
                      </a>
                    </li>
                  </ul>
                </li>
                <li class="pX-20 pY-15 ta-c bdT">
                  <span>
                    <a href="" class="c-grey-600 cH-blue fsz-sm td-n">View All Notifications <i class="ti-angle-right fsz-xs mL-10"></i></a>
                  </span>
                </li>
              </ul>
            </li>
            <li class="notifications dropdown">
              <span class="counter bgc-blue">3</span>
              <a href="" class="dropdown-toggle no-after" data-toggle="dropdown">
                <i class="ti-email"></i>
              </a>
              <ul class="dropdown-menu">
                <li class="pX-20 pY-15 bdB">
                  <i class="ti-email pR-10"></i>
                  <span class="fsz-sm fw-600 c-grey-900">Emails</span>
                </li>
                <li>
                  <ul class="ovY-a pos-r scrollable lis-n p-0 m-0 fsz-sm">
                    <li>
                      <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                        <div class="peer mR-15">
                          <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/1.jpg" alt="">
                        </div>
                        <div class="peer peer-greed">
                          <div>
                            <div class="peers jc-sb fxw-nw mB-5">
                              <div class="peer">
                                <p class="fw-500 mB-0">John Doe</p>
                              </div>
                              <div class="peer">
                                <small class="fsz-xs">5 mins ago</small>
                              </div>
                            </div>
                            <span class="c-grey-600 fsz-sm">
                              Want to create your own customized data generator for your app...
                            </span>
                          </div>
                        </div>
                      </a>
                    </li>
                    <li>
                      <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                        <div class="peer mR-15">
                          <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/2.jpg" alt="">
                        </div>
                        <div class="peer peer-greed">
                          <div>
                            <div class="peers jc-sb fxw-nw mB-5">
                              <div class="peer">
                                <p class="fw-500 mB-0">Moo Doe</p>
                              </div>
                              <div class="peer">
                                <small class="fsz-xs">15 mins ago</small>
                              </div>
                            </div>
                            <span class="c-grey-600 fsz-sm">
                              Want to create your own customized data generator for your app...
                            </span>
                          </div>
                        </div>
                      </a>
                    </li>
                    <li>
                      <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                        <div class="peer mR-15">
                          <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/3.jpg" alt="">
                        </div>
                        <div class="peer peer-greed">
                          <div>
                            <div class="peers jc-sb fxw-nw mB-5">
                              <div class="peer">
                                <p class="fw-500 mB-0">Lee Doe</p>
                              </div>
                              <div class="peer">
                                <small class="fsz-xs">25 mins ago</small>
                              </div>
                            </div>
                            <span class="c-grey-600 fsz-sm">
                              Want to create your own customized data generator for your app...
                            </span>
                          </div>
                        </div>
                      </a>
                    </li>
                  </ul>
                </li>
                <li class="pX-20 pY-15 ta-c bdT">
                  <span>
                    <a href="email.html" class="c-grey-600 cH-blue fsz-sm td-n">View All Email <i class="fs-xs ti-angle-right mL-10"></i></a>
                  </span>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1" data-toggle="dropdown">
                <div class="peer mR-10">
                  <img class="w-2r bdrs-50p" src="https://randomuser.me/api/portraits/men/10.jpg" alt="">
                </div>
                <div class="peer">
                  <span class="fsz-sm c-grey-900">John Doe</span>
                </div>
              </a>
              <ul class="dropdown-menu fsz-sm">
                <li>
                  <a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                    <i class="ti-settings mR-10"></i>
                    <span>Setting</span>
                  </a>
                </li>
                <li>
                  <a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                    <i class="ti-user mR-10"></i>
                    <span>Profile</span>
                  </a>
                </li>
                <li>
                  <a href="email.html" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                    <i class="ti-email mR-10"></i>
                    <span>Messages</span>
                  </a>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                    <i class="ti-power-off mR-10"></i>
                    <span>Logout</span>
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
      <!-- ### $App Screen Content ### -->
      <main class='main-content bgc-grey-100'>
        <div id='mainContent'></div>
      </main>
      <!-- ### $App Screen Footer ### -->
      <footer class="bdT ta-c p-30 lh-0 fsz-sm c-grey-600">
        <span>Copyright © 2017 Designed by <a href="https://colorlib.com" target='_blank' title="Colorlib">Colorlib</a>. All rights reserved.</span>
      </footer>
    </div>
  </div>
  <script src="{% static 'js/vendor.js' %}"></script>
  <script src="{% static 'js/bundle.js' %}"></script>
</body>

</html>

myproject/core/templates/google-maps.html
{% extends "base.html" %}
{% load static %}
{% block title %}Google Maps{% endblock title %}
{% block content %}
<div class="container-fluid">
  <h4 class="c-grey-900 mT-10 mB-30">Google Maps</h4>
  <div class="row">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <h6 class="c-grey-900 mB-20">Google Maps</h6>
        <div id="google-map" style="padding-bottom: 75%;"></div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

myproject/core/templates/includes/footer.html
<footer class="bdT ta-c p-30 lh-0 fsz-sm c-grey-600">
  <span>Copyright © 2019 Designed by <a href="https://colorlib.com" target='_blank' title="Colorlib">Colorlib</a>. All rights reserved.</span>
</footer>

myproject/core/templates/includes/sidebar.html
{% load static %}
<!-- #Left Sidebar ==================== -->
<div class="sidebar">
  <div class="sidebar-inner">
    <!-- ### $Sidebar Header ### -->
    <div class="sidebar-logo">
      <div class="peers ai-c fxw-nw">
        <div class="peer peer-greed">
          <a class="sidebar-link td-n" href="index.html">
            <div class="peers ai-c fxw-nw">
              <div class="peer">
                <div class="logo">
                  <img src="{% static 'img/logo.png' %}" alt="">
                </div>
              </div>
              <div class="peer peer-greed">
                <h5 class="lh-1 mB-0 logo-text">Adminator</h5>
              </div>
            </div>
          </a>
        </div>
        <div class="peer">
          <div class="mobile-toggle sidebar-toggle">
            <a href="" class="td-n">
              <i class="ti-arrow-circle-left"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
    <!-- ### $Sidebar Menu ### -->
    <ul class="sidebar-menu scrollable pos-r">
      <li class="nav-item mT-30 active">
        <a class="sidebar-link" href="{% url 'core:index' %}">
          <span class="icon-holder">
            <i class="c-blue-500 ti-home"></i>
          </span>
          <span class="title">Dashboard</span>
        </a>
      </li>
      <li class="nav-item">
        <a class='sidebar-link' href="{% url 'core:email' %}">
          <span class="icon-holder">
            <i class="c-brown-500 ti-email"></i>
          </span>
          <span class="title">Email</span>
        </a>
      </li>
      <li class="nav-item">
        <a class='sidebar-link' href="{% url 'core:compose' %}">
          <span class="icon-holder">
            <i class="c-blue-500 ti-share"></i>
          </span>
          <span class="title">Compose</span>
        </a>
      </li>
      <li class="nav-item">
        <a class='sidebar-link' href="{% url 'core:calendar' %}">
          <span class="icon-holder">
            <i class="c-deep-orange-500 ti-calendar"></i>
          </span>
          <span class="title">Calendar</span>
        </a>
      </li>
      <li class="nav-item">
        <a class='sidebar-link' href="{% url 'core:chat' %}">
          <span class="icon-holder">
            <i class="c-deep-purple-500 ti-comment-alt"></i>
          </span>
          <span class="title">Chat</span>
        </a>
      </li>
      <li class="nav-item">
        <a class='sidebar-link' href="{% url 'core:charts' %}">
          <span class="icon-holder">
            <i class="c-indigo-500 ti-bar-chart"></i>
          </span>
          <span class="title">Charts</span>
        </a>
      </li>
      <li class="nav-item">
        <a class='sidebar-link' href="{% url 'core:forms' %}">
          <span class="icon-holder">
            <i class="c-light-blue-500 ti-pencil"></i>
          </span>
          <span class="title">Forms</span>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="sidebar-link" href="{% url 'core:ui' %}">
          <span class="icon-holder">
            <i class="c-pink-500 ti-palette"></i>
          </span>
          <span class="title">UI Elements</span>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="dropdown-toggle" href="javascript:void(0);">
          <span class="icon-holder">
            <i class="c-orange-500 ti-layout-list-thumb"></i>
          </span>
          <span class="title">Tables</span>
          <span class="arrow">
            <i class="ti-angle-right"></i>
          </span>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a class='sidebar-link' href="{% url 'core:basic_table' %}">Basic Table</a>
          </li>
          <li>
            <a class='sidebar-link' href="{% url 'core:datatable' %}">Data Table</a>
          </li>
        </ul>
      </li>
      <li class="nav-item dropdown">
        <a class="dropdown-toggle" href="javascript:void(0);">
          <span class="icon-holder">
            <i class="c-purple-500 ti-map"></i>
          </span>
          <span class="title">Maps</span>
          <span class="arrow">
            <i class="ti-angle-right"></i>
          </span>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a href="{% url 'core:google_maps' %}">Google Map</a>
          </li>
          <li>
            <a href="{% url 'core:vector_maps' %}">Vector Map</a>
          </li>
        </ul>
      </li>
      <li class="nav-item dropdown">
        <a class="dropdown-toggle" href="javascript:void(0);">
          <span class="icon-holder">
            <i class="c-red-500 ti-files"></i>
          </span>
          <span class="title">Pages</span>
          <span class="arrow">
            <i class="ti-angle-right"></i>
          </span>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a class='sidebar-link' href="{% url 'core:blank' %}">Blank</a>
          </li>
          <li>
            <a class='sidebar-link' href="{% url 'core:p404' %}">404</a>
          </li>
          <li>
            <a class='sidebar-link' href="{% url 'core:p500' %}">500</a>
          </li>
          <li>
            <a class='sidebar-link' href="{% url 'core:signin' %}">Sign In</a>
          </li>
          <li>
            <a class='sidebar-link' href="{% url 'core:signup' %}">Sign Up</a>
          </li>
        </ul>
      </li>
      <li class="nav-item dropdown">
        <a class="dropdown-toggle" href="javascript:void(0);">
          <span class="icon-holder">
            <i class="c-teal-500 ti-view-list-alt"></i>
          </span>
          <span class="title">Multiple Levels</span>
          <span class="arrow">
            <i class="ti-angle-right"></i>
          </span>
        </a>
        <ul class="dropdown-menu">
          <li class="nav-item dropdown">
            <a href="javascript:void(0);">
              <span>Menu Item</span>
            </a>
          </li>
          <li class="nav-item dropdown">
            <a href="javascript:void(0);">
              <span>Menu Item</span>
              <span class="arrow">
                <i class="ti-angle-right"></i>
              </span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <a href="javascript:void(0);">Menu Item</a>
              </li>
              <li>
                <a href="javascript:void(0);">Menu Item</a>
              </li>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>

myproject/core/templates/vector-maps.html
{% extends "base.html" %}
{% load static %}
{% block title %}Vector Maps{% endblock title %}
{% block content %}
<div class="container-fluid">
  <h4 class="c-grey-900 mT-10 mB-30">Vector Maps</h4>
  <div class="row">
    <div class="col-md-12">
      <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <h6 class="c-grey-900 mB-20">Jquery Vector Maps</h6>
        <div id="world-map-marker"></div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}